### ISSUE TITLE
이슈1

### ISSUE THREAD

**Issue by www-r** [TripleA-Project/TripleA-FrontEnd#1]
## 설명
여기에 간략한 설명을 적어주세요

## 절차(Task)
- [ ] task
- [ ] task

**Comment by Ryan-TheLion** [comment]
팀장 허락없이는 닫을수 없습니다

**Comment by Ryan-TheLion** [comment]
디스코드 웹훅테스트용이라서 해당 이슈는 닫도록 하겠습니다
