### ISSUE TITLE
[Library] zagjs 사용 가능 여부 테스트

### ISSUE THREAD

**Issue by www-r** [TripleA-Project/TripleA-FrontEnd#6]
[zagjs 공식 사이트 링크](https://zagjs.com/)
1. Next.js + TailwindCSS 환경에서 동작하는 것 확인했습니다.
2. 현재까지 나온 디자인 시안에서 zagjs 라이브러리를 사용해서 만들만한 눈에 띄는 것은 없었습니다.
3. 다른 headless UI 라이브러리(테스트는 안 해봤습니다) :  [HeadlessUI](https://headlessui.com/) , [radixUI](https://www.radix-ui.com/) , [reachUI](https://github.com/reach/reach-ui)

![Image](https://github.com/TripleA-Project/TripleA-FrontEnd/assets/117294002/41d61973-1095-4cf3-8c74-5b60e6858f06)

```
const data = [
  { title: "Watercraft", content: "Sample accordion content: watercraft" },
  { title: "Automobiles", content: "Sample accordion content: automobile" },
  { title: "Aircrafts", content: "Sample accordion content: aircrafts" },
]


 <div {...api.rootProps}>
      {data.map((item) => (
        <div {...api.getItemProps({ value: item.title })} key={item.title} >
          <h3>
            <button {...api.getTriggerProps({ value: item.title })} className="underline text-red-400">
              {item.title}
            </button>
          </h3>
          <div {...api.getContentProps({ value: item.title })}>
            {item.content}
          </div>
        </div>
      ))
      }
    </div>
```

**Comment by www-r** [comment]
참고 사이트 : https://jbee.io/react/headless-concept/ , https://www.howdy-mj.me/design/headless-components

**Comment by Ryan-TheLion** [comment]
headless UI 라이브러리를 사용할 경우 기존 UI 프레임워크(MUI 등 ...)보다 스타일링이 자유로울 것 같아 좋을 것 같습니다. 

다만, 
1. 해당 라이브러리의 컴포넌트에 저희가 원하는 기능이 없을 경우에는 도입을 하지 못하고 직접 새로 만들어야 될 수 있기 때문에 도입하기 이전에 그 부분을 신경써서 고려해보고 결정하는 것이 좋을 것 같고 (공식문서 확인해보기 등...)
2. 생각보다 지원해주는 컴포넌트가 많은 것 같지는 않아보여서 

디자인 시안이 1차로 나온 이후에 논의해서 도입해보는 것도 괜찮을 것 같습니다
